TaskManager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('ToDoList.urls')),
]

ToDoList/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name="home"),
    path('register/', views.UserRegisterView.as_view(), name="register"),
    path('edit_user/', views.UserEditView.as_view(),  name="edit_user"),
    path('password/', views.PasswordsChangeView.as_view(), name="password_change"),
    path('tasks/', views.TaskView.as_view(), name="task_view"),
    path('create_task/', views.CreateTaskView.as_view(), name="create_task"),
    path('edit_task/<int:pk>', views.EditTaskView.as_view(), name="edit_task"),
    path('delete_task/<int:pk>', views.DeteletaskView.as_view(), name="delete_task"),

]

ToDoList/models.py
from django.db import models
from django.contrib.auth.models import User


class Task(models.Model):
    FINISHED = [
        ('C', 'Completed'),
        ('T', 'To be done'),
    ]
    # Used OnetoMany relationship for User
    User = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name="task", null=True)
    title = models.CharField(max_length=32, null=True)
    description = models.TextField(max_length=255, null=True)
    done = models.CharField(choices=FINISHED, max_length=1, null=True)

    class Meta:
        verbose_name = ("Task")
        verbose_name_plural = ("Tasks")
        ordering = ['-done']

    def __str__(self):
        return str(self.title)

ToDoList/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django import forms


# Instead of creating new User model I modified one from auth.models
class SingUpForm(UserCreationForm):
    email = forms.EmailField(required=False)
    first_name = forms.CharField(max_length=255, required=False)
    last_name = forms.CharField(max_length=255, required=False)

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1',
                  'password2')


# Had to reduce Users options to change like SUPERUSER to basic ones
class EditUserForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password')

ToDoList/views.py
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import get_object_or_404

from .models import Task
from .forms import SingUpForm, EditUserForm


class HomePageView(generic.ListView):
    template_name = "home.html"
    model = Task


class TaskView(generic.ListView):
    template_name = "task.html"
    model = Task


# Task will automatically get User_id so USER can't do it manually
class CreateTaskView(generic.CreateView):
    template_name = "add_task.html"
    model = Task
    fields = ['title', 'description', 'done']
    success_url = reverse_lazy('task_view')

    def form_valid(self, form):
        form.instance.User_id = self.request.user.id
        return super().form_valid(form)


class DeteletaskView(generic.DeleteView):
    template_name = 'delete_task.html'
    model = Task
    success_url = reverse_lazy('task_view')


class EditTaskView(generic.UpdateView):
    template_name = "edit_task.html"
    model = Task
    fields = ['title', 'description', 'done']
    success_url = reverse_lazy('task_view')


# Bonus Login system
class UserRegisterView(generic.CreateView):
    form_class = SingUpForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('login')


class UserEditView(generic.UpdateView):
    form_class = EditUserForm
    template_name = "registration/edit_user.html"
    success_url = reverse_lazy('home')

    def get_object(self):
        user = get_object_or_404(Task, pk=self.request.user.id)
        return user


class PasswordsChangeView(PasswordChangeView):
    form_class = PasswordChangeForm
    template_name = 'registration/change_password.html'
    success_url = reverse_lazy('home')

ToDoList/templates/add_task.html
{% extends 'base.html' %}

{% block title %}
    Create task 
{% endblock  %}

{%block content%}
    {%if user.is_authenticated%}
        </br><h1>Add new task</h1></br>
        {%load crispy_forms_tags %}
        <form method ='post'>
        {% csrf_token %}
        {{form|crispy}}
        <button class = 'btn btn-secondary'>Create Task</button>
        </br></br>
    {% else %}
        </br>
        <h3> You have to login to access Task Manager app</h3> 
        <p><strong>You can login <a href= "{% url 'login' %}"> here</a></strong></br>
        <strong>Don't have an account? Create one <a href = "{% url 'register' %}"> here </a></strong></p>
    {% endif %}
{% endblock %}

ToDoList/templates/base.html
<!DOCTYPE html>
<html>
<head>
<title>
{% block title %} Task Manager {% endblock title %}
</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
</head>
<body>


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                    <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>

                    <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'register' %}">Register</a>
                    </li>
               
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'task_view' %}">Task Manager</a>
                    </li>

                </ul>

                <ul class="navbar-nav ml-auto">

                    {%if user.is_authenticated == False%}
                    <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'login' %}">Login</a>
                    </li>
                    {% endif %}

                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" style="color: #ffffff"  id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Logged as
                         {% if user.first_name %}
                         {{user.first_name}} 
                         {% else %}
                         {{user.username}} 
                         {% endif %}
                          
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'edit_user' %}">User settings</a></li>
                        </ul>
                    </li>

                    <li>
                    <a class="nav-link active" aria-current="page" href="{% url 'logout' %}">Logout</a>
                    </li>
                    
                    {% endif %}
                </ul>


            </div>
        </div>
    </nav>

    

    <div class="container" style = "max-width:850px"> 
    {% block content %}
    {% endblock content %}
    </div>



    <script src="https://code.jquery.com/jquery.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    </body>  
</html>

ToDoList/templates/delete_task.html
{% extends 'base.html' %}

{% block title %}
    Delete Task
{% endblock  %}

{%block content%}
    {%if user.id == task.User_id%}
        </br><h1>Delete task</h1></br>
        {%load crispy_forms_tags %}
        <form method ='post'>
        {% csrf_token %}
        <strong> You are about to delete <i>"{{task.title}}"</i> </strong></br></br>
        <button class = 'btn btn-secondary'>Delete</button>
        </br></br>
    {% else %}
        <strong><p>You can't be here and you know it! <a href = '/login'>Here</a></p></strong>
    {% endif %}
{% endblock %}

ToDoList/templates/edit_task.html
{% extends 'base.html' %}

{% block title %}
    Edit Task
{% endblock  %}

{%block content%}
    {%if user.id == task.User_id%}
        </br><h1>Edit task</h1></br>
        {%load crispy_forms_tags %}
        <form method ='post'>
        {% csrf_token %}
        {{form|crispy }}
        <button class = 'btn btn-secondary'>Save </button>
        </br></br>
    {% else %}
      <strong><p>You can't be here and you know it! <a href = '/login'>Here</a></p></strong>
    {% endif %}
{% endblock %}

ToDoList/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <div class = "container " style = "max-width:400"></br>
        <h2>Welcome ThinkEasy Team</h2></br>
        <p>To access Task Manager you have to register and login.
        After that you can access Task Manager through navbar under "Task Manager button".
        Within the app you can create, describe, edit, delete and change tasks status.</p>
    </div>
{% endblock %}

ToDoList/templates/task.html
{% extends 'base.html' %}

{% block content %}
    {% if user.is_authenticated %}</br>
        {% if user.first_name %}
            <h2>Welcome {{user.first_name}}</h2>
        {% else %}
            <h2>Welcome {{user.username}}</h2>
        {% endif %}

        <ul></br></br>
            {% if user.task.all %}
            {% for task in user.task.all%}
                <li><strong>{{task.title}}</strong>
                - {{task.description}} - {{task.get_done_display}}</br>

            <i><a href = "{% url 'edit_task' task.pk %}">Edit Task</a>
                <a href = "{% url 'delete_task' task.pk %}">Delete Task</a></i></li></br>
            {% endfor %}
            <i><a href = "{% url 'create_task'%}">Add Task</a></i>
            {% else %}
            No tasks yet. <a href = "{% url 'create_task'%}">Add Task?</a>
            {% endif %}
        </ul>
    {% else %}
        </br>
        <h3> You have to login to access Task Manager app</h3> 
        <p><strong>You can login <a href= "{% url 'login' %}"> here</a></strong></br>
        <strong>Don't have an account? Create one <a href = "{% url 'register' %}"> here </a></strong></p>
    {% endif %}
{% endblock %}